OSPF_R1:
  - router ospf 1
  - router-id 1.1.1.1
  - network 192.168.2.0 0.0.0.255 area 0
  - network 192.168.3.0 0.0.0.255 area 0
  - network 192.168.255.255 255.255.255.255 area 0
  - exit
  - int gig2
  - ip ospf authentication
  - ip ospf auth message-digest
  - ip ospf message-digest-key 1 MD5 xgroup

OSPF_R2:
  - router ospf 1
  - router-id 2.2.2.2
  - network 192.168.2.0 0.0.0.255 area 0
  - network 192.168.4.0 0.0.0.255 area 0
  - exit
  - int gig2
  - ip ospf authentication
  - ip ospf auth message-digest
  - ip ospf message-digest-key 1 MD5 xgroup




